name = "All the Mons"
author = "ATMTeam"
version = "0.14.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c7b4a710fcfed4580033cfa2de3455a4915bbc24b9061fd0262eedaa4eecb89"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"

[options]
acceptable-game-versions = ["fabric"]
