name = "All the Mons"
author = "ATMTeam"
version = "0.14.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13ef049013a396c95f7b78399696968542d666eee10b90971abcf3a489d821e5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"

[options]
acceptable-game-versions = ["fabric"]
