name = "All the Mons"
author = "ATMTeam"
version = "0.14.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f09b1fe92227af58f147bc8ad8d0f11306b90edcf8c6d632d4e6f1fff780d82f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"

[options]
acceptable-game-versions = ["fabric"]
